# -*- coding: utf-8 -*-
"""Tarea3(FGerbier-IValdebenito).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b779aW4AArSlEPi0uG_Lbzsm6URfVxjx
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

dataframe = pd.read_csv("WA_Fn-UseC_-HR-Employee-Attrition.csv")
dataframe.head()

#1. ¿Cuál es el ingreso mensual promedio de los empleados que no realizan viajes de negocios y tienen  una satisfacción laboral superior al promedio?
satisfaccion_laboral = dataframe["JobSatisfaction"].mean()
empleados_nonegocios = dataframe[dataframe["BusinessTravel"] == "Non-Travel"]
empleados_filtrados = empleados_nonegocios[empleados_nonegocios["JobSatisfaction"] > satisfaccion_laboral]
mensual = empleados_filtrados["MonthlyIncome"].mean()
print(f'El ingreso mensual promedio es de los empleados que no realizan viajes de negocios es: {mensual}')

#2.¿Cuáles son los rangos de ingresos mensuales por género y nivel educativo entre los empleados que han dejado la empresa?

desempleados = dataframe[dataframe["Attrition"] == "Yes"]
r2 = desempleados.groupby(["Gender", "Education"])["MonthlyIncome"].agg([min, max])
r2

#3.¿Cómo varía el porcentaje de incremento salarial ('PercentSalaryHike') entre los empleados que han trabajado en más de 3 compañías ('NumCompaniesWorked' > 3), agrupado por departamento?
empleados_mascompañias = dataframe[dataframe["NumCompaniesWorked"] > 3]
r3 = empleados_mascompañias.groupby("Department")["PercentSalaryHike"].mean().round(2)
r3

#4.¿Existe relación entre los años en la empresa ('YearsAtCompany') y la satisfacción con el ambiente
#laboral ('EnvironmentSatisfaction') para empleados con más de 5 años de antigüedad muestre un gráfico asociado?

empleados_masantiguedad = dataframe[dataframe["YearsAtCompany"] > 5]
r4 = empleados_masantiguedad.groupby("EnvironmentSatisfaction")["YearsAtCompany"].mean()
r4.plot(kind="bar", color="steelblue")
plt.show()

#5. ¿Cuál combinación de estado civil y departamento tiene la menor satisfacción general
#('JobSatisfaction'), y cuáles podrían ser las razones basadas en los datos disponibles?
r5 = dataframe.groupby(["MaritalStatus", "Department"])["JobSatisfaction"].mean()
satisfaccion_general = r5.idxmin()
valor_satisfaccion_general= r5.min()
r5

print(f'La combinación de estado civil y departamento con la menor satisfacción laboral es: {satisfaccion_general} con una satisfacción promedio de {valor_satisfaccion_general}')

#6. ¿Influye la distancia desde el hogar al trabajo en la decisión de trabajar horas extras entre los
#empleados con un nivel de involucramiento laboral bajo ('JobInvolvement' = 1)?

r6 = dataframe[dataframe["JobInvolvement"] == 1]
distancia = r6.groupby("OverTime")["DistanceFromHome"].mean()
distancia
print(f"Entre los empleados con bajo involucramiento laboral, la distancia que influye el trabajo es de {distancia['Yes']:.2f} km para los que realizan horas extras y {distancia['No']:.2f} km para quienes no realizan horas extras.")

#7. ¿Cómo se distribuye la edad ('Age') entre los empleados con un alto nivel de involucramiento en el
# trabajo ('JobInvolvement' = 4), y existe alguna tendencia de edad notable en este subgrupo?

r7 = dataframe[dataframe['JobInvolvement'] == 4]

plt.figure(figsize=(10, 6))
sns.histplot(r7['Age'], kde=True, color="steelblue")
plt.title('Distribución de Edad')
plt.xlabel('Edad')
plt.ylabel('Frecuencia')
plt.show()
print(f'La distribución de edad para empleados con alto nivel de involucramiento laboral (JobInvolvement = 4) está centrada alrededor de los {r7["Age"].median()} años.')

#8. ¿Existen diferencias significativas en los ingresos mensuales entre los empleados que han recibido
# promociones en los últimos 2 años en comparación con aquellos que no las han recibido?
# Comparar ingresos mensuales entre empleados promovidos y no promovidos en los últimos 2 años

promovidos = dataframe[dataframe['YearsSinceLastPromotion'] <= 2]
no_promovidos = dataframe[dataframe['YearsSinceLastPromotion'] > 2]

plt.figure(figsize=(10, 6))
sns.boxplot(data=[promovidos['MonthlyIncome'], no_promovidos['MonthlyIncome']], notch=True, palette="Oranges")
plt.xticks([0, 1], ['Promovidos', 'No Promovidos'])
plt.title('Comparación de ingresos mensuales entre promovidos/no promovidos en los últimos 2 años')
plt.ylabel('Ingreso Mensual')
plt.show()
print(f'El ingreso mensual promedio de los empleados promovidos en los últimos 2 años es de {promovidos["MonthlyIncome"].mean():.2f}, mientras que el ingreso promedio de los no promovidos es de {no_promovidos["MonthlyIncome"].mean():.2f}.')

#9. ¿Cómo impactan los niveles de satisfacción con las relaciones ('RelationshipSatisfaction') en la
# probabilidad de atrición (desgaste) de los empleados, considerando diferentes niveles de ingresos
# mensuales y de educación?

desgaste = dataframe[dataframe['Attrition'] == 'Yes']

plt.figure(figsize=(10, 6))
sns.scatterplot(data=desgaste, x='MonthlyIncome', y='RelationshipSatisfaction', hue='Education', size='Education', palette='Oranges')
plt.title('Impacto satisfacción - desgaste en empleados (Considera: nivel educación/Ingresos Mensuales)')
plt.xlabel('Ingreso Mensual')
plt.ylabel('Satisfacción en Relaciones')
plt.show()
print(f'Los empleados con menor satisfacción en relaciones y bajos ingresos muestran mayor probabilidad de atrición, con una satisfacción promedio de {desgaste["RelationshipSatisfaction"].mean():.2f}.')

#10. ¿Varía significativamente la proporción de empleados que dejaron la compañía ('ACrition' = 'Yes')
# entre los diferentes departamentos, y cómo se relaciona esto con la satisfacción del ambiente
# laboral ('EnvironmentSatisfaction')?

departamento = pd.crosstab(dataframe['Department'], dataframe['Attrition'], normalize='index') * 100
plt.figure(figsize=(10, 6))
sns.heatmap(departamento, annot=True, cmap='Oranges')
plt.title('Proporción de "atrición" por departamento')
plt.ylabel('Departamento')
plt.xlabel('Atrición')
plt.show()

# Analizar la relación con la satisfacción del ambiente laboral
plt.figure(figsize=(10, 6))
sns.boxplot(x='Attrition', y='EnvironmentSatisfaction', hue='Department', data=dataframe, palette="Oranges")
plt.title('Relación entre atrición y satisfacción en ambiente laboral por departamento')
plt.show()
print(f'La proporción de atrición más alta se observa en el departamento de {dataframe[dataframe["Attrition"] == "Yes"]["Department"].mode()[0]}, relacionado con niveles bajos de satisfacción en el ambiente laboral.')