# -*- coding: utf-8 -*-
"""trabajo_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oh7mM74mAkQN8H0jy7-E-_iE9S9IXBV-
"""

import pandas as pd

dato = ['Casillas','Ramos','Pique','Puyol','Capdevila','Xabi Alonso','Busquets','Xavi Hernandez','Pedrito','Iniesta','Villa']
serie= pd.Series(data=dato)
serie

index = [1,15,3,5,11,14,16,8,18,6,7]
serie =  pd.Series(data=dato,index=index)
serie

Dict = {
    "Casillas":1, "Ramos":15, "Pique":3, "Puyol":5, "Capdevila":11, "Xabi Alonso":14, "Busquets":16, "Xavi Hernandez":8, "Pedrito":18, "Iniesta":6,
    "Villa":7
}
serie = pd.Series(Dict)
serie

d = {'Name':['Casillas','Ramos','Pique','Puyol','Capdevila','Xabi Alonso','Busquets','Xavi Hernandez','Pedrito','Iniesta','Villa'],
     'demarcation':['Goalkeeper','Right Back','Centre Back','Centre Back','Left Back','Defensive Midfielder','Defensive Midfielder','Midfielder','Midfielder','Midfielder','Forward'],
     'team':['Real Madrid','Real Madrid','FC Barcelona','FC Barcelona','Real Madrid','Real Madrid','FC Barcelona','FC Barcelona','Real Madrid','FC Barcelona','Real Madrid'],
  }
index = [1, 15, 3, 5, 11, 14, 16, 8, 18, 6, 7]
df = pd.DataFrame(d, index=index)

df

df.loc[10] = ['Cesc','Forward','Arsenal']
df